---
- name: Execute custom commands
  command:
    cmd: "cephadm shell -- {{ cephadm_command }} {{ item }}"
  register: cephadm_commands_result
  with_items: "{{ cephadm_commands }}"
  become: true
  changed_when: true
  when: cephadm_commands | length > 0

  delegate_to: "{{ cephadm_bootstrap_host }}"
  run_once: true
