namespace: "stackhpc"
name: "cephadm"
version: "1.5.1"
readme: "README.md"
authors:
  - "Michal Nasiadka"
  - "Bartosz Bezak"
  - "John Garbutt"
  - "Mark Goddard"
license:
  - "Apache-2.0"
tags:
  - cephadm
repository: "https://github.com/stackhpc/ansible-collection-cephadm"
