namespace: "stackhpc"
name: "cephadm"
version: "1.20.0"
readme: "README.md"
authors:
  - "Michal Nasiadka"
  - "Bartosz Bezak"
  - "John Garbutt"
  - "Mark Goddard"
license:
  - "Apache-2.0"
tags:
  - cephadm
  - infrastructure
description: "Ansible roles to create and manage cephadm-based Ceph deployments"
repository: "https://github.com/stackhpc/ansible-collection-cephadm"
