---
- name: Get cluster fsid
  command:
    cmd: "cephadm shell -- ceph fsid"
  when: cephadm_fsid | length == 0
  become: true
  register: cephadm_fsid_current
  changed_when: false

- name: Template out service_spec.yml
  vars:
    fsid: "{{ cephadm_fsid if cephadm_fsid | length > 0 else cephadm_fsid_current.stdout }}"
  copy:
    content: "{{ cephadm_service_spec | to_nice_yaml if cephadm_service_spec is mapping else cephadm_service_spec }}"
    dest: "/var/run/ceph/{{ fsid }}/service_spec.yml"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Apply service spec
  command:
    cmd: >
         cephadm shell --
         ceph orch apply -i /var/run/ceph/service_spec.yml
  become: true
  changed_when: true
  when:
    - cephadm_service_spec | length > 0
    - inventory_hostname == cephadm_bootstrap_host
