---
- name: Ensure centos-release-ceph-octopus package is removed
  dnf:
    name: "centos-release-ceph-octopus"
    state: absent
  when: not cephadm_custom_repos | bool
  become: true

- name: Add Ceph gpgkey
  rpm_key:
    key: "https://download.ceph.com/keys/release.asc"
    state: present
  when: not cephadm_custom_repos | bool
  become: true

- name: Ensure Ceph repositories are defined
  yum_repository:
    file: "ceph"
    name: "ceph-{{ item.0 + '-' + item.1 if item.0 == 'noarch' else item.1 }}"
    description: "Ceph {{ item.1 }} repo {{ item.0 }}"
    baseurl: "https://download.ceph.com/rpm-{{ item.1 }}/el{{ ansible_facts.distribution_major_version }}/{{ item.0 }}"
    gpgcheck: true
    gpgkey: "https://download.ceph.com/keys/release.asc"
    state: "{{ 'present' if item.1 == cephadm_ceph_release else 'absent' }}"
  when: not cephadm_custom_repos | bool
  become: true
  loop: "{{ cephadm_rpm_repos | product(cephadm_ceph_releases) | list }}"

- name: Install cephadm package
  dnf:
    name: "cephadm"
    install_weak_deps: false
    state: "{{ 'latest' if cephadm_package_update | bool else 'present' }}"
    update_cache: true
  become: true
  timeout: 600
  ignore_errors: true
  register: cephadm_install
  retries: 3
  delay: 20


# NOTE(Alex-Welsh): The cephadm install task sometimes hangs indefinitely after
# the package is installed. This is a workaround to ensure the playbook
# completes properly.
- name: Ensure Cephadm package has installed properly
  dnf:
    name: "cephadm"
    install_weak_deps: false
    state: "{{ 'latest' if cephadm_package_update | bool else 'present' }}"
    update_cache: true
  become: true
  timeout: 60
  when: cephadm_install is failed
