---
- name: Install centos-release-ceph-octopus package
  dnf:
    name: "centos-release-ceph-octopus"
    state: present
  when: not cephadm_custom_repos | bool
  become: true

- name: Install cephadm package
  dnf:
    name: "cephadm"
    state: present
  become: true
