---
- name: Ensure centos-release-ceph-octopus package is removed
  dnf:
    name: "centos-release-ceph-octopus"
    state: absent
  when: not cephadm_custom_repos | bool
  become: true

- name: Add Ceph gpgkey
  rpm_key:
    key: "https://download.ceph.com/keys/release.asc"
    state: present
  when: not cephadm_custom_repos | bool
  become: true

- name: Ensure Ceph repositories are defined
  yum_repository:
    file: "ceph"
    name: "ceph-{{ item.1 }}"
    description: "Ceph repo {{ item.0 }}"
    baseurl: "https://download.ceph.com/rpm-{{ item.1 }}/el8/{{ item.0 }}"
    gpgcheck: yes
    gpgkey: "https://download.ceph.com/keys/release.asc"
    state: "{{ 'present' if item.1 == cephadm_ceph_release else 'absent' }}"
  when: not cephadm_custom_repos | bool
  become: true
  loop: "{{ cephadm_rpm_repos | product(cephadm_ceph_versions) | list }}"

- name: Install cephadm package
  dnf:
    name: "cephadm"
    state: "{{ 'latest' if cephadm_package_update | bool else 'present' }}"
  become: true
