---
- name: Populate service facts
  service_facts:

- name: Set cephadm_bootstrap
  set_fact:
    cephadm_bootstrap: "{{ ansible_facts.services | dict2items | selectattr('key', 'match', '^ceph.*') | list | length == 0 }}"
