---
- job:
    parent: base
    name: cephadm-base
    pre-run: tests/playbooks/pre.yml
    run: tests/playbooks/run.yml
    post-run: tests/playbooks/post.yml
    timeout: 7200
    post-timeout: 1800
