---
- project:
    check:
      jobs:
        - cephadm-jammy-multinode-docker-reef
        - cephadm-jammy-multinode-podman-reef
        - tox-linters
    gate:
      jobs:
        - cephadm-jammy-multinode-docker-reef
        - cephadm-jammy-multinode-podman-reef
